FORMAT: 1A
HOST: http://www.google.com

# 373-nba
373-nba is an API for NBA IDB

## Teams Collection [/teams]
### List all Teams [GET]
+ Response 200 (application/hal+json)

        [
            {
                "id": 1,
                "name": "Heat",
                "location: "Miami"
            },
            {
                "id": 2,
                "name": "Lakers",
                "location: "Los Angeles"
            },
            {
                "id": 3,
                "name": "Spurs",
                "location: "San Antonio"
            }
        ]


## Team [/teams/{id}]
A single Team object with all its details

+ Parameters
    + id (required, int) ... Unique team ID in the form of an integer

+ Model (application/hal+json)
 
    + Body
 
            {
                "id": 1,
                "name": "Heat",
                "location: "Miami"
            }

### Retrieve a single Team [GET]
 
+ Response 200 (application/json)
 
    [Team][]
    
+ Response 404 (application/json)
 
        { 
            "error": "Resource not found" 
        }


## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]



## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
