FORMAT: 1A
HOST: http://nbaidb.pythonanywhere.com

# 373-nba
373-nba is an API for NBA IDB

# Group Team
Data pertaining to NBA Teams

## Teams Collection [/api/teams/?format=json]
### List all Teams [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Spurs",
                "location": "San Antonio, TX",
                "coach": "Gregg Popovich",
                "gm": "R. C. Buford",
                "owner": "Peter Holt",
                "twitter": "https://twitter.com/spurs",
                "twitter_widget": "491472793976836097",
                "logo": "http://www.sports-logos-screensavers.com/user/San_Antonio_Spurs2.jpg",
                "finals_years": "2005, 2007, 2013, 2014",
                "mvps": "none",
                "finals_mvps": "Tim Duncan, Tony Parker",
                "stadium": "AT&T Center",
                "map_lat": "29.427134",
                "map_lng": "-98.437466",
                "map_address": "1 AT&T Center Pkwy San Antonio, TX 78219"
            },
            {
                "id": 2,
                "name": "Heat",
                "location": "Miami, FL",
                "coach": "Erik Spoelstra",
                "gm": "Pat Riley",
                "owner": "Micky Arison",
                "twitter": "https://twitter.com/MiamiHEAT",
                "twitter_widget": "492365616179720193",
                "logo": "http://blog.yellowdoggdesigns.com/wp-content/uploads/2013/06/miami-heat-logo.jpg",
                "finals_years": "2006, 2011, 2012, 2013, 2014",
                "mvps": "Lebron James",
                "finals_mvps": "Dwyane Wade, Lebron James",
                "stadium": "AmericanAirlines Arena",
                "map_lat": "25.781696",
                "map_lng": "-80.186980",
                "map_address": "601 Biscayne Blvd Miami, FL 33132"
            },
            {
                "id": 3,
                "name": "Lakers",
                "location": "Los Angeles, CA",
                "coach": "vacant",
                "gm": "Mitch Kupchak",
                "owner": "Jerry Buss Family Trust",
                "twitter": "https://twitter.com/Lakers",
                "twitter_widget": "491476151773048832",
                "logo": "http://upload.wikimedia.org/wikipedia/en/9/9a/Los_Angeles_Lakers_logo.png",
                "finals_years": "2008, 2009, 2010",
                "mvps": "Kobe Bryant",
                "finals_mvps": "Kobe Bryant",
                "stadium": "STAPLES Center",
                "map_lat": "34.043236",
                "map_lng": "-118.274925",
                "map_address": "1111 S Figueroa St Los Angeles, CA 90015"
            },
            {
                "id": 4,
                "name": "Suns",
                "location": "Phoenix, AZ",
                "coach": "Jeff Hornacek",
                "gm": "Ryan McDonough",
                "owner": "Robert Sarver",
                "twitter": "https://twitter.com/Suns",
                "twitter_widget": "492364562545405953",
                "logo": "http://img3.wikia.nocookie.net/__cb20130726175325/logopedia/images/f/fe/Phoenix_Suns_2013_Logo.png",
                "finals_years": "none",
                "mvps": "Steve Nash",
                "finals_mvps": "none",
                "stadium": "U.S Airways Center",
                "map_lat": "33.446119",
                "map_lng": "-112.071082",
                "map_address": "201 E Jefferson St Phoenix, AZ 85004"
            },
            {
                "id": 5,
                "name": "Mavericks",
                "location": "Dallas, TX",
                "coach": "Rick Carlisle",
                "gm": "Don Nelson",
                "owner": "Mark Cuban",
                "twitter": "https://twitter.com/dallasmavs",
                "twitter_widget": "492364793114673152",
                "logo": "http://electricmaninc.com/wp-content/uploads/2011/03/dallas_mavericks_logo_yyq71.png",
                "finals_years": "2006, 2011",
                "mvps": "Dirk Nowitzki",
                "finals_mvps": "Dirk Nowitzki",
                "stadium": "American Airlines Center",
                "map_lat": "32.790979",
                "map_lng": "-96.810459",
                "map_address": "2500 Victory Ave Dallas, TX 75219"
            },
            {
                "id": 6,
                "name": "Celtics",
                "location": "Boston, MA",
                "coach": "Brad Stevens",
                "gm": "Danny Ainge",
                "owner": "Boston Basketball Partners",
                "twitter": "https://twitter.com/celtics",
                "twitter_widget": "492364939097432065",
                "logo": "http://img4.wikia.nocookie.net/__cb20120119223258/nba2k/images/b/bf/Boston_Celtics_Logo.png",
                "finals_years": "2008, 2010",
                "mvps": "none",
                "finals_mvps": "Paul Pierce",
                "stadium": "TD Garden",
                "map_lat": "42.366253",
                "map_lng": "-71.062144",
                "map_address": "100 Legends Way Boston, MA 02114"
            },
            {
                "id": 7,
                "name": "Wizards",
                "location": "Washington, D.C.",
                "coach": "Randy Wittman",
                "gm": "Ernie Grunfeld",
                "owner": "Ted Leonsis",
                "twitter": "https://twitter.com/WashWizards",
                "twitter_widget": "492365944711155713",
                "logo": "http://tiger.towson.edu/~mpiazz2/Wizards/Washington_Wizards4.png",
                "finals_years": "none",
                "mvps": "none",
                "finals_mvps": "none",
                "stadium": "Verizon Center",
                "map_lat": "38.898254",
                "map_lng": "-77.020949",
                "map_address": "601 F St NW Washington, DC 20004"
            },
            {
                "id": 8,
                "name": "Cavaliers",
                "location": "Cleveland, OH",
                "coach": "David Blatt",
                "gm": "David Griffin",
                "owner": "Dan Gilbert",
                "twitter": "https://twitter.com/cavs",
                "twitter_widget": "492365086292312064",
                "logo": "http://img4.wikia.nocookie.net/__cb20070605174502/halo/images/a/a3/Cleveland_Cavs_logo.png",
                "finals_years": "2007",
                "mvps": "Lebron James",
                "finals_mvps": "none",
                "stadium": "Quicken Loans Arena",
                "map_lat": "41.496864",
                "map_lng": "-81.688354",
                "map_address": "1 Center Ct Cleveland, OH 44115"
            },
            {
                "id": 9,
                "name": "Bulls",
                "location": "Chicago, IL",
                "coach": "Tom Thibodeau",
                "gm": "Gar Forman",
                "owner": "Jerry Reinsdorf",
                "twitter": "https://twitter.com/chicagobulls",
                "twitter_widget": "492365362415943681",
                "logo": "http://www.blainebpa.org/WebsiteSTATE/images/Chicago-Bulls-Logo.png",
                "finals_years": "none",
                "mvps": "Derrick Rose",
                "finals_mvps": "none",
                "stadium": "United Center",
                "map_lat": "41.880911",
                "map_lng": "-87.674165",
                "map_address": "1901 W Madison St Chicago, IL 60612"
            },
            {
                "id": 10,
                "name": "Thunder",
                "location": "Oklahoma City, OK",
                "coach": "Scott Brooks",
                "gm": "Sam Presti",
                "owner": "Professional Basketball Club LLC",
                "twitter": "https://twitter.com/okcthunder",
                "twitter_widget": "491469252390445056",
                "logo": "http://img2.wikia.nocookie.net/__cb20120119223616/nba2k/images/7/74/Oklahoma_City_Thunder_Logo.png",
                "finals_years": "2012",
                "mvps": "Kevin Durant",
                "finals_mvps": "none",
                "stadium": "Chesapeake Energy Arena",
                "map_lat": "35.463688",
                "map_lng": "-97.514846",
                "map_address": "100 W Reno Ave Oklahoma City, OK 73102"
            }
        ]


## Team [/api/teams/{id}/?format=json]
A single Team object with all its details

+ Parameters
    + id (required, int) ... Unique team ID in the form of an integer


### Retrieve a single Team [GET]
 
+ Response 200 (application/json)
 
        {
            "id": 1,
            "name": "Spurs",
            "location": "San Antonio, TX",
            "coach": "Gregg Popovich",
            "gm": "R. C. Buford",
            "owner": "Peter Holt",
            "twitter": "https://twitter.com/spurs",
            "twitter_widget": "491472793976836097",
            "logo": "http://www.sports-logos-screensavers.com/user/San_Antonio_Spurs2.jpg",
            "finals_years": "2005, 2007, 2013, 2014",
            "mvps": "none",
            "finals_mvps": "Tim Duncan, Tony Parker",
            "stadium": "AT&T Center",
            "map_lat": "29.427134",
            "map_lng": "-98.437466",
            "map_address": "1 AT&T Center Pkwy San Antonio, TX 78219"
        }
    
+ Response 404 (application/json)
 
        {
            "detail": "Not found"
        }


# Group Player 
Data pertaining to NBA Players

## Players Collection [/api/players/?format=json]
### List all Players [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Tim Duncan",
                "position": "PF",
                "education": "Wake Forest",
                "years_exp": 17,
                "twitter": "https://twitter.com/TimSlamDuncan",
                "twitter_widget": "492366152106926082",
                "nickname": "\"The Big Fundamental\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/215.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/3uTCIPiuG5A",
                "current_team": "Spurs",
                "gp": 1254,
                "gs": 1252,
                "minpg": 34.8,
                "fgperc": 50.6,
                "ftperc": 69.4,
                "reb": 11.1,
                "ast": 3.1,
                "blk": 2.2,
                "stl": 0.7,
                "pts": 19.9,
                "finals_years": "1999, 2003, 2005, 2007, 2013, 2014",
                "finals_teams": "Spurs",
                "mvp_years": "2002, 2003",
                "finalsmvp_years": "2005",
                "allnba_years": "1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2007, 2013",
                "alldef_years": "1999, 2000, 2001, 2002, 2003, 2005, 2007, 2008"
            },
            {
                "id": 2,
                "name": "Lebron James",
                "position": "PF",
                "education": "St. Vincent-St. Mary High School",
                "years_exp": 11,
                "twitter": "https://twitter.com/KingJames",
                "twitter_widget": "492366292033089536",
                "nickname": "\"King James\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/6CgqhHva56w",
                "current_team": "Cavaliers",
                "gp": 842,
                "gs": 841,
                "minpg": 39.5,
                "fgperc": 49.7,
                "ftperc": 74.7,
                "reb": 7.2,
                "ast": 6.9,
                "blk": 0.8,
                "stl": 1.7,
                "pts": 27.5,
                "finals_years": "2007, 2011, 2012, 2013, 2014",
                "finals_teams": "Cavaliers, Heat",
                "mvp_years": "2010, 2012, 2013",
                "finalsmvp_years": "2012, 2013",
                "allnba_years": "2006, 2008, 2009, 2010, 2011, 2012, 2013, 2014",
                "alldef_years": "2009, 2010, 2011, 2012, 2013"
            },
            {
                "id": 3,
                "name": "Kobe Bryant",
                "position": "SG",
                "education": "Lower Merion High School",
                "years_exp": 18,
                "twitter": "https://twitter.com/kobebryant",
                "twitter_widget": "492367374134153216",
                "nickname": "\"Black Mamba\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/110.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/hZFtrsoFCDI",
                "current_team": "Lakers",
                "gp": 1245,
                "gs": 1097,
                "minpg": 36.6,
                "fgperc": 45.4,
                "ftperc": 83.8,
                "reb": 5.3,
                "ast": 4.8,
                "blk": 0.5,
                "stl": 1.5,
                "pts": 25.5,
                "finals_years": "2000, 2001, 2002, 2004, 2008, 2009, 2010",
                "finals_teams": "Lakers",
                "mvp_years": "2008",
                "finalsmvp_years": "2009, 2010",
                "allnba_years": "2002, 2003, 2004, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013",
                "alldef_years": "2000, 2003, 2004, 2006, 2007, 2008, 2009. 2010, 2011"
            },
            {
                "id": 4,
                "name": "Steve Nash",
                "position": "PG",
                "education": "Santa Clara",
                "years_exp": 18,
                "twitter": "https://twitter.com/SteveNash",
                "twitter_widget": "491701650977849346",
                "nickname": "\"Captain Canada\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/592.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/9Wp49pG3-g0",
                "current_team": "Lakers",
                "gp": 1217,
                "gs": 1053,
                "minpg": 31.3,
                "fgperc": 49.0,
                "ftperc": 90.4,
                "reb": 3.0,
                "ast": 8.5,
                "blk": 0.1,
                "stl": 0.7,
                "pts": 14.3,
                "finals_years": "none",
                "finals_teams": "none",
                "mvp_years": "2005, 2006",
                "finalsmvp_years": "none",
                "allnba_years": "2005, 2006, 2007",
                "alldef_years": "none"
            },
            {
                "id": 5,
                "name": "Dwyane Wade",
                "position": "SG",
                "education": "Marquette",
                "years_exp": 11,
                "twitter": "https://twitter.com/DwyaneWade",
                "twitter_widget": "492366409570062336",
                "nickname": "\"Flash\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1987.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/pPVzvf3nPxQ",
                "current_team": "Heat",
                "gp": 719,
                "gs": 710,
                "minpg": 36.6,
                "fgperc": 49.2,
                "ftperc": 76.5,
                "reb": 5.0,
                "ast": 6.0,
                "blk": 1.0,
                "stl": 1.8,
                "pts": 24.3,
                "finals_years": "2006, 2011, 2012, 2013, 2014",
                "finals_teams": "Heat",
                "mvp_years": "none",
                "finalsmvp_years": "2006",
                "allnba_years": "2009, 2010",
                "alldef_years": "none"
            },
            {
                "id": 6,
                "name": "Tony Parker",
                "position": "PG",
                "education": "International",
                "years_exp": 13,
                "twitter": "https://twitter.com/tonyparker",
                "twitter_widget": "492367764066017280",
                "nickname": "\"TP\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1015.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/vbBawRDWuks",
                "current_team": "Spurs",
                "gp": 940,
                "gs": 927,
                "minpg": 32.6,
                "fgperc": 49.5,
                "ftperc": 75.2,
                "reb": 3.0,
                "ast": 6.0,
                "blk": 0.1,
                "stl": 0.9,
                "pts": 17.1,
                "finals_years": "2003, 2005, 2007, 2013, 2014",
                "finals_teams": "Spurs",
                "mvp_years": "none",
                "finalsmvp_years": "2007",
                "allnba_years": "none",
                "alldef_years": "none"
            },
            {
                "id": 7,
                "name": "Dirk Nowitzki",
                "position": "PF",
                "education": "International",
                "years_exp": 16,
                "twitter": "https://twitter.com/swish41",
                "twitter_widget": "492368227297525760",
                "nickname": "\"Dirk\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/609.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/TcgQmdefWw0",
                "current_team": "Mavericks",
                "gp": 1188,
                "gs": 1157,
                "minpg": 35.9,
                "fgperc": 47.6,
                "ftperc": 87.9,
                "reb": 8.1,
                "ast": 2.6,
                "blk": 0.9,
                "stl": 0.9,
                "pts": 22.5,
                "finals_years": "2006, 2011",
                "finals_teams": "Mavericks",
                "mvp_years": "2007",
                "finalsmvp_years": "2011",
                "allnba_years": "2005, 2006, 2007, 2009",
                "alldef_years": "none"
            },
            {
                "id": 8,
                "name": "Kevin Durant",
                "position": "SF",
                "education": "Texas",
                "years_exp": 7,
                "twitter": "https://twitter.com/KDTrey5",
                "twitter_widget": "492368476929941504",
                "nickname": "\"KD\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3202.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/GIFiWKFSsh0",
                "current_team": "Thunder",
                "gp": 542,
                "gs": 542,
                "minpg": 38.2,
                "fgperc": 47.9,
                "ftperc": 88.2,
                "reb": 6.9,
                "ast": 3.5,
                "blk": 1.0,
                "stl": 1.3,
                "pts": 27.4,
                "finals_years": "2012",
                "finals_teams": "Thunder",
                "mvp_years": "2014",
                "finalsmvp_years": "none",
                "allnba_years": "2010, 2011, 2012, 2013",
                "alldef_years": "none"
            },
            {
                "id": 9,
                "name": "Kawhi Leonard",
                "position": "SF",
                "education": "San Diego State",
                "years_exp": 3,
                "twitter": "https://twitter.com/kawhileonard",
                "twitter_widget": "492368668357951488",
                "nickname": "\"The Future\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6450.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/Gptiz36HLlQ",
                "current_team": "Spurs",
                "gp": 188,
                "gs": 161,
                "minpg": 28.0,
                "fgperc": 50.5,
                "ftperc": 80.3,
                "reb": 5.8,
                "ast": 1.6,
                "blk": 0.6,
                "stl": 1.6,
                "pts": 10.9,
                "finals_years": "2013, 2014",
                "finals_teams": "Spurs",
                "mvp_years": "none",
                "finalsmvp_years": "2014",
                "allnba_years": "none",
                "alldef_years": "none"
            },
            {
                "id": 10,
                "name": "Derrick Rose",
                "position": "PG",
                "education": "Memphis",
                "years_exp": 5,
                "twitter": "https://twitter.com/drose",
                "twitter_widget": "492368838441181184",
                "nickname": "\"D-Rose\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3456.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/Plt4b2RHT48",
                "current_team": "Bulls",
                "gp": 289,
                "gs": 288,
                "minpg": 36.6,
                "fgperc": 46.0,
                "ftperc": 81.5,
                "reb": 3.8,
                "ast": 6.8,
                "blk": 0.4,
                "stl": 0.9,
                "pts": 20.8,
                "finals_years": "none",
                "finals_teams": "none",
                "mvp_years": "2011",
                "finalsmvp_years": "none",
                "allnba_years": "2011",
                "alldef_years": "none"
            },
            {
                "id": 11,
                "name": "Paul Pierce",
                "position": "SF",
                "education": "Kansas",
                "years_exp": 16,
                "twitter": "https://twitter.com/paulpierce34",
                "twitter_widget": "492368968967917568",
                "nickname": "\"The Truth\"",
                "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/662.png&w=350&h=254",
                "highlights": "https://www.youtube.com/embed/TOZELH5TTog",
                "current_team": "Wizards",
                "gp": 1177,
                "gs": 1167,
                "minpg": 36.1,
                "fgperc": 44.7,
                "ftperc": 80.7,
                "reb": 5.9,
                "ast": 3.8,
                "blk": 0.6,
                "stl": 1.4,
                "pts": 21.3,
                "finals_years": "2008, 2010",
                "finals_teams": "Celtics",
                "mvp_years": "none",
                "finalsmvp_years": "2008",
                "allnba_years": "2002, 2003, 2008, 2009",
                "alldef_years": "none"
            }
        ]


## Player [/api/players/{id}/?format=json]
A single Player object with all its details

+ Parameters
    + id (required, int) ... Unique player ID in the form of an integer


### Retrieve a single Player [GET]
 
+ Response 200 (application/json)
    
        {
            "id": 3,
            "name": "Kobe Bryant",
            "position": "SG",
            "education": "Lower Merion High School",
            "years_exp": 18,
            "twitter": "https://twitter.com/kobebryant",
            "twitter_widget": "492367374134153216",
            "nickname": "\"Black Mamba\"",
            "photo": "http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/110.png&w=350&h=254",
            "highlights": "https://www.youtube.com/embed/hZFtrsoFCDI",
            "current_team": "Lakers",
            "gp": 1245,
            "gs": 1097,
            "minpg": 36.6,
            "fgperc": 45.4,
            "ftperc": 83.8,
            "reb": 5.3,
            "ast": 4.8,
            "blk": 0.5,
            "stl": 1.5,
            "pts": 25.5,
            "finals_years": "2000, 2001, 2002, 2004, 2008, 2009, 2010",
            "finals_teams": "Lakers",
            "mvp_years": "2008",
            "finalsmvp_years": "2009, 2010",
            "allnba_years": "2002, 2003, 2004, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013",
            "alldef_years": "2000, 2003, 2004, 2006, 2007, 2008, 2009. 2010, 2011"
        }
    
+ Response 404 (application/json)
 
        {
            "detail": "Not found"
        }


# Group Season
Data pertaining to NBA Seasons

## Seasons Collection [/api/years/?format=json]
### List all Seasons [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "year": "2005",
                "finals_logo": "http://upload.wikimedia.org/wikipedia/en/thumb/6/65/NBA_Finals_05.png/200px-NBA_Finals_05.png",
                "finals_recap": "The 2005 NBA Finals was the championship round of the 2004-05 National Basketball Association season. The San Antonio Spurs of the Western Conference faced the Detroit Pistons of the Eastern Conference for the title, with the Spurs holding home court advantage and the Pistons as defending champions. The series was played under a best-of-seven format. (Unlike the previous three rounds, the team with home court advantage hosted games one, two, six, and seven if all were necessary). It also marked the Pistons first NBA Finals loss to a team other than the Lakers since 1988.\r\nThe Spurs won the series four games to three in the first NBA Finals to go to a Game 7 since 1994. The games were broadcast on ABC, with Al Michaels and Hubie Brown commentating. National radio coverage was provided by ESPN Radio through announcers Jim Durham and Dr. Jack Ramsay.",
                "highlights": "https://www.youtube.com/embed/BxIa4XrHh4Q",
                "all_nba": "Tim Duncan, Allen Iverson, Steve Nash, Dirk Nowitzki, Shaquille O'Neal",
                "all_def": "Bruce Bowen, Tim Duncan, Kevin Garnett, Larry Hughes, Ben Wallace",
                "reg_mvp": "Steve Nash",
                "finals_mvp": "Tim Duncan",
                "champion": "Spurs"
            },
            {
                "id": 2,
                "year": "2006",
                "finals_logo": "http://michaelaltschuler.files.wordpress.com/2011/05/versus-dallas-mavericks-vs-miami-heat.jpg",
                "finals_recap": "The 2006 NBA Finals was the championship series of the 2005\u201306 National Basketball Association season. The Miami Heat won the title in six games over the Dallas Mavericks, becoming the third team\u2014after the 1969 Celtics and the 1977 Trail Blazers\u2014to win a championship after trailing 0\u20132 in the series. Heat guard Dwyane Wade was named Most Valuable Player of the series.\r\n",
                "highlights": "https://www.youtube.com/embed/VOZY99zZ-o8",
                "all_nba": "Lebron James, Dirk Nowitzki, Shaquille O\u2019Neal, Kobe Bryant, Steve Nash",
                "all_def": "Bruce Bowen, Ben Wallace, Andrei Kirilenko, Ron Artest, Kobe Bryant, Jason Kidd",
                "reg_mvp": "Steve Nash",
                "finals_mvp": "Dwyane Wade",
                "champion": "Heat"
            },
            {
                "id": 3,
                "year": "2007",
                "finals_logo": "http://upload.wikimedia.org/wikipedia/en/7/79/2007_NBA_Finals.png",
                "finals_recap": "The 2007 NBA Finals was the championship series of the 2006\u201307 National Basketball Association season, and was the conclusion of the 2007 NBA Playoffs. The best-of-seven series was played between the Western Conference champion San Antonio Spurs and the Eastern Conference champion Cleveland Cavaliers. This was Cleveland's first trip to the NBA Finals in their franchise history and San Antonio's fourth. The Spurs swept the Cavaliers 4-0. Tony Parker was named the series' MVP. The series was televised on ABC under the ESPN on ABC branding, and produced low television ratings.\r\n",
                "highlights": "https://www.youtube.com/embed/9aF6RJCfqf4",
                "all_nba": "Dirk Nowitzki, Tim Duncan, Amar\u2019e Stoudemire, Steve Nash, Kobe Bryant",
                "all_def": "Tim Duncan, Bruce Bowen, Marcus Camby, Kobe Bryant, Raja Bell",
                "reg_mvp": "Dirk Nowitzki",
                "finals_mvp": "Tony Parker",
                "champion": "Spurs"
            },
            {
                "id": 4,
                "year": "2008",
                "finals_logo": "http://content.sportslogos.net/logos/6/981/full/gc0ehbgvuonjd0jgj148lgg47.gif",
                "finals_recap": "The 2008 NBA Finals were held June 5 through June 17 of 2008, to decide the winner of the 2007\u201308 NBA season, and conclude the season's playoffs. The Boston Celtics, top-seeded champions of the Eastern Conference, defeated the Los Angeles Lakers, top-seeded champions of the Western Conference, four games to two in a best-of-seven series. This was Boston's first title since 1986 and 17th overall.\r\n2008 marked the first time since 2000 that the top seeds from both conferences met in the Finals and the first time since 2003 that any top seeded team played in the NBA finals. The Lakers appeared in the Finals for the first time since 2004 and a record 29th time overall. The Celtics appeared in the Finals for the first time since 1987 and second-best 20th time overall.\r\n",
                "highlights": "https://www.youtube.com/embed/qzcayb9KEis",
                "all_nba": "Kevin Garnett, Lebron James, Dwight Howard, Kobe Bryant, Chris Paul",
                "all_def": "Kevin Garnett, Tim Duncan, Marcus Camby, Kobe Bryant, Bruce Bowen",
                "reg_mvp": "Kobe Bryant",
                "finals_mvp": "Paul Pierce",
                "champion": "Celtics"
            },
            {
                "id": 5,
                "year": "2009",
                "finals_logo": "http://content.sportslogos.net/logos/6/981/full/5rxl4j98r10cevf7eyz5dryqn.gif",
                "finals_recap": "The 2009 NBA Finals was the National Basketball Association (NBA) championship series for the 2008-09 season. The best-of-seven playoff was contested between the Los Angeles Lakers, champions of the Western Conference and defending Western Conference champions, and the Orlando Magic, champions of the Eastern Conference. The Lakers defeated the Magic, four games to one, to win the franchise's 15th NBA championship. The 63rd edition of the championship series was played between June 4 and June 14 and was broadcast on ABC.\r\n",
                "highlights": "https://www.youtube.com/embed/gpRmbhPg98o",
                "all_nba": "Lebron James, Dirk Nowitzki, Dwight Howard, Kobe Bryant, Dwyane Wade",
                "all_def": "Dwight Howard, Kobe Bryant, Lebron James, Chris Paul, Kevin Garnett",
                "reg_mvp": "Lebron James",
                "finals_mvp": "Kobe Bryant",
                "champion": "Lakers"
            },
            {
                "id": 6,
                "year": "2010",
                "finals_logo": "http://upload.wikimedia.org/wikipedia/en/6/6a/2010_NBA_Finals.png",
                "finals_recap": "The 2010 NBA Finals was the National Basketball Association (NBA) championship series for the 2009\u201310 season. The best-of-seven playoff was contested between the Los Angeles Lakers, champions of the Western Conference and defending NBA champions, and the Boston Celtics, champions of the Eastern Conference. The Lakers defeated the Celtics, four games to three, to win the franchise's 16th NBA championship. The 64th[1] edition of the championship series was played between June 3 and June 17, was broadcast on ABC, and was watched by an average of 18.1 million people.\r\n",
                "highlights": "https://www.youtube.com/embed/dfGQHTpTLkk",
                "all_nba": "Lebron James, Kevin Durant, Dwight Howard, Kobe Bryant, Dwyane Wade",
                "all_def": "Dwight Howard, Kobe Bryant, Lebron James, Rajon Rondo, Gerald Wallace",
                "reg_mvp": "Lebron James",
                "finals_mvp": "Kobe Bryant",
                "champion": "Lakers"
            },
            {
                "id": 7,
                "year": "2011",
                "finals_logo": "http://sports-odds.com/images/stories/2011-nba-finals-logo.jpg",
                "finals_recap": "The 2011 NBA Finals was the championship series of the 2010\u201311 season of the National Basketball Association (NBA) and the conclusion of the season's playoffs. The Western Conference champion Dallas Mavericks defeated the Eastern Conference champion Miami Heat, 4\u20132, to win their first NBA title. Dallas became the latest NBA team from Texas to win its first title, after the Houston Rockets won back-to-back titles in 1994 and 1995, and the San Antonio Spurs won in 1999, 2003, 2005, and 2007; all three Texas NBA teams have now won at least one NBA Championship. It was also the first time in four years that the Los Angeles Lakers did not make the finals.\r\n",
                "highlights": "https://www.youtube.com/embed/5vXQAz7Cy4o",
                "all_nba": "Lebron James, Kevin Durant, Dwight Howard, Kobe Bryant, Derrick Rose",
                "all_def": "Dwight Howard, Kobe Bryant, Lebron James, Rajon Rondo, Kevin Garnett",
                "reg_mvp": "Derrick Rose",
                "finals_mvp": "Dirk Nowitzki",
                "champion": "Mavericks"
            },
            {
                "id": 8,
                "year": "2012",
                "finals_logo": "http://upload.wikimedia.org/wikipedia/en/9/99/2012_NBA_Finals_Logo.jpg",
                "finals_recap": "The 2012 NBA Finals was the championship series of the 2011\u201312 season of the National Basketball Association (NBA) and the conclusion of the season's playoffs. The Eastern Conference champion Miami Heat defeated the Western Conference champion Oklahoma City Thunder, 4\u20131, to win their second NBA title. Miami's LeBron James was named the Finals MVP.\r\nThis marked the fourth time in franchise history that the Oklahoma City Thunder appeared in the NBA Finals and the first time since moving from Seattle to Oklahoma City in 2008. The franchise had previously appeared as the Seattle SuperSonics in 1996. It also marked the Miami Heat's third appearance in the NBA Finals. The Heat previously appeared in 2006 and 2011, both times against the Dallas Mavericks.\r\n",
                "highlights": "https://www.youtube.com/embed/7rHoCOqpaDw",
                "all_nba": "Lebron James, Kevin Durant, Dwight Howard, Kobe Bryant, Chris Paul",
                "all_def": "Dwight Howard, Serge Ibaka, Lebron James, Chris Paul, Tony Allen",
                "reg_mvp": "Lebron James",
                "finals_mvp": "Lebron James",
                "champion": "Heat"
            },
            {
                "id": 9,
                "year": "2013",
                "finals_logo": "http://upload.wikimedia.org/wikipedia/en/e/e1/2013_NBA_Finals_Logo.jpg",
                "finals_recap": "The 2013 NBA Finals was the championship series of the 2012\u201313 NBA season and the conclusion of the season's playoffs. The Eastern Conference champion Miami Heat defeated the Western Conference champion San Antonio Spurs to win their second straight title. The Finals began with Game 1 on June 6, and ended with Game 7 on June 20.\r\n",
                "highlights": "https://www.youtube.com/embed/L9gwRnf5c2w",
                "all_nba": "Lebron James, Kevin Durant, Tim Duncan, Kobe Bryant, Chris Paul",
                "all_def": "Joakim Noah, Tyson Chandler, Serge Ibaka, Lebron James, Chris Paul, Tony Allen",
                "reg_mvp": "Lebron James",
                "finals_mvp": "Lebron James",
                "champion": "Heat"
            },
            {
                "id": 10,
                "year": "2014",
                "finals_logo": "http://sports-glutton.com/wp-content/uploads/2013/06/2013-NBA-Finals.jpg",
                "finals_recap": "The 2014 NBA Finals was the championship series of the 2013\u201314 season of the National Basketball Association (NBA) and the conclusion of the season's playoffs. The Western Conference champion San Antonio Spurs defeated the Eastern Conference champion Miami Heat in five games (4\u20131) for the Spurs' fifth NBA championship in the franchise's history. The Spurs outscored the Heat in the series by the largest average point differential (14.0) in Finals history. San Antonio's Kawhi Leonard was named the Finals Most Valuable Player (MVP), and became the third-youngest recipient of the award.",
                "highlights": "https://www.youtube.com/embed/xnIjCqO7W0g",
                "all_nba": "Lebron James, Kevin Durant, Joakim Noah, James Harden, Chris Paul",
                "all_def": "Joakim Noah, Paul George, Serge Ibaka, Chris Paul, Andre Iguodala",
                "reg_mvp": "Kevin Durant",
                "finals_mvp": "Kawhi Leonard",
                "champion": "Spurs"
            }
        ]


## Season [/api/years/{id}/?format=json]
A single Season object with all its details

+ Parameters
    + id (required, int) ... Unique season ID in the form of an integer
    

### Retrieve a single Season [GET]
 
+ Response 200 (application/json)
 
        {
            "id": 7,
            "year": "2011",
            "finals_logo": "http://sports-odds.com/images/stories/2011-nba-finals-logo.jpg",
            "finals_recap": "The 2011 NBA Finals was the championship series of the 2010\u201311 season of the National Basketball Association (NBA) and the conclusion of the season's playoffs. The Western Conference champion Dallas Mavericks defeated the Eastern Conference champion Miami Heat, 4\u20132, to win their first NBA title. Dallas became the latest NBA team from Texas to win its first title, after the Houston Rockets won back-to-back titles in 1994 and 1995, and the San Antonio Spurs won in 1999, 2003, 2005, and 2007; all three Texas NBA teams have now won at least one NBA Championship. It was also the first time in four years that the Los Angeles Lakers did not make the finals.\r\n",
            "highlights": "https://www.youtube.com/embed/5vXQAz7Cy4o",
            "all_nba": "Lebron James, Kevin Durant, Dwight Howard, Kobe Bryant, Derrick Rose",
            "all_def": "Dwight Howard, Kobe Bryant, Lebron James, Rajon Rondo, Kevin Garnett",
            "reg_mvp": "Derrick Rose",
            "finals_mvp": "Dirk Nowitzki",
            "champion": "Mavericks"
        }
    
+ Response 404 (application/json)
 
        { 
            "detail": "Not found"
        }




