FORMAT: 1A
HOST: http://nbaidb.pythonanywhere.com/

# 373-nba
373-nba is an API for NBA IDB

# Group Team
Data pertaining to NBA Teams

## Teams Collection [/teams]
### List all Teams [GET]
+ Response 200 (application/hal+json)

        [
            {
                "id": 1,
                "name": "Heat",
                "location": "Miami",
                "coach": "Erik Spoelstra",
                "gm": "Pat Riley",
                "owner": "Micky Arison",
                "twitter": <https://twitter.com/MiamiHEAT>,
                "logo": <http://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/200px-Miami_Heat_logo.svg.png>
            },
            {
                "id": 2,
                "name": "Lakers",
                "location: "Los Angeles",
                "coach": "",
                "gm": "Mitch Kupchak",
                "owner": "Jerry Buss Family Trust",
                "twitter": <https://twitter.com/Lakers>,
                "logo": <http://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/LosAngeles_Lakers_logo.svg/200px-LosAngeles_Lakers_logo.svg.png>
            },
            {
                "id": 3,
                "name": "Spurs",
                "location": "San Antonio",
                "coach": "Gregg Popovich",
                "gm": "R.C. Buford",
                "owner": "Peter Holt",
                "twitter": <https://twitter.com/spurs>,
                "logo": <http://upload.wikimedia.org/wikipedia/en/thumb/a/a2/San_Antonio_Spurs.svg/200px-San_Antonio_Spurs.svg.png>
            }
        ]


## Team [/teams/{id}]
A single Team object with all its details

+ Parameters
    + id (required, int) ... Unique team ID in the form of an integer

+ Model (application/hal+json)
 
    + Body
 
            {
                "id": 1,
                "name": "Heat",
                "location": "Miami",
                "coach": "Erik Spoelstra",
                "gm": "Pat Riley",
                "owner": "Micky Arison",
                "twitter": <https://twitter.com/MiamiHEAT>,
                "logo": <http://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/200px-Miami_Heat_logo.svg.png>
            }

### Retrieve a single Team [GET]
 
+ Response 200 (application/json)
 
    [Team][]
    
+ Response 404 (application/json)
 
        { 
            "error": "Resource not found" 
        }

# Group Player 
Data pertaining to NBA Players

## Players Collection [/players]
### List all Players [GET]
+ Response 200 (application/hal+json)

        [
            {
                "id": 1,
                "name": "Kobe Bryant",
                "position": "SG",
                "education": "Lower Merion High School",
                "years_exp": 18,
                "twitter" = <https://twitter.com/kobebryant>,
                "photo" = <http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/110.png&w=350&h=254>
            },
            {
                "id": 2,
                "name": "Tim Duncan",
                "position": "PF",
                "education": "Wake Forest",
                "years_exp": 17,
                "twitter" = <https://twitter.com/TimSlamDuncan>,
                "photo" = <http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/215.png&w=350&h=254>
            },
            {
                "id": 3,
                "name": "Lebron James",
                "position": "SF",
                "education": "WSt. Vincent-St. Mary High School",
                "years_exp": 11,
                "twitter" = <https://twitter.com/KingJames>,
                "photo" = <http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png&w=350&h=254>
            }
        ]


## Player [/players/{id}]
A single Player object with all its details

+ Parameters
    + id (required, int) ... Unique player ID in the form of an integer

+ Model (application/hal+json)
 
    + Body
 
            {
                "id": 1,
                "name": "Kobe Bryant",
                "position": "SG",
                "education": "Lower Merion High School",
                "years_exp": 18,
                "twitter" = <https://twitter.com/kobebryant>,
                "photo" = <http://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/110.png&w=350&h=254>
            }

### Retrieve a single Player [GET]
 
+ Response 200 (application/json)
 
    [Player][]
    
+ Response 404 (application/json)
 
        { 
            "error": "Resource not found" 
        }

# Group Season

## Seasons Collection [/seasons]
### List all Seasons [GET]
+ Response 200 (application/hal+json)

        [
            {
                "id": 1,
                "year": "2014",
                "champion": "Spurs"
            },
            {
                "id": 2,
                "year": "2013",
                "champion": "Heat"
            },
            {
                "id": 3,
                "year": "2012",
                "champion": "Heat"
            }
        ]


## Season [/seasons/{id}]
A single Season object with all its details

+ Parameters
    + id (required, int) ... Unique season ID in the form of an integer

+ Model (application/hal+json)
 
    + Body
 
            {
                "id": 1,
                "year": "2014",
                "champion": "Spurs"
            }

### Retrieve a single Season [GET]
 
+ Response 200 (application/json)
 
    [Season][]
    
+ Response 404 (application/json)
 
        { 
            "error": "Resource not found" 
        }




